package net.psycris.wow.combatlog;

public enum Specialization {
    DEATH_KNIGHT_BLOOD(250),
    DEATH_KNIGHT_FROST(251),
    DEATH_KNIGHT_UNHOLY(252),
    DEMON_HUNTER_HAVOC(577),
    DEMON_HUNTER_VENGEANCE(581),
    DRUID_BALANCE(102),
    DRUID_FERAL(103),
    DRUID_GUARDIAN(104),
    DRUID_RESTORATION(105),
    HUNTER_BEAST_MASTERY(253),
    HUNTER_MARKSMANSHIP(254),
    HUNTER_SURVIVAL(255),
    MAGE_ARCANE(62),
    MAGE_FIRE(63),
    MAGE_FROST(64),
    MONK_BREWMASTER(268),
    MONK_WINDWALKER(269),
    MONK_MISTWEAVER(270),
    PALADIN_HOLY(65),
    PALADIN_PROTECTION(66),
    PALADIN_RETRIBUTION(70),
    PRIEST_DISCIPLINE(256),
    PRIEST_HOLY(257),
    PRIEST_SHADOW(258),
    ROGUE_ASSASSINATION(259),
    ROGUE_OUTLAW(260),
    ROGUE_SUBTLETY(261),
    SHAMAN_ELEMENTAL(262),
    SHAMAN_ENHANCEMENT(263),
    SHAMAN_RESTORATION(264),
    WARLOCK_AFFLICTION(265),
    WARLOCK_DEMONOLOGY(266),
    WARLOCK_DESTRUCTION(267),
    WARRIOR_ARMS(71),
    WARRIOR_FURY(72),
    WARRIOR_PROTECTION(73);

    private final int value;

    Specialization(final int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }
}
